<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="ExDoc v0.37.1">
    <meta name="project" content="Elixir v1.17.3">


    <title>try, catch, and rescue — Elixir v1.17.3</title>

    <link rel="stylesheet" href="dist/html-elixir-PD7PAHEK.css" />

      <link rel="canonical" href="https://hexdocs.pm/elixir/try-catch-and-rescue.html" />

    <script defer src="dist/sidebar_items-3D721A5F.js"></script>
    <script defer src="docs_config.js"></script>
    <script>var Module={arguments: ["eval.avm"] }</script>
    <script defer src="dist/AtomVM.js"></script>
    <script defer src="dist/html-KNMUZUZQ.js"></script>

  </head>
  <body>
    <script>(()=>{var t="ex_doc:settings",e="dark";var o="dark",s="light";var E="sidebar_state",n="closed";var r="sidebar_width";var a="sidebar-open";var i=new URLSearchParams(window.location.search),S=i.get("theme")||JSON.parse(localStorage.getItem(t)||"{}").theme;(S===o||S!==s&&window.matchMedia("(prefers-color-scheme: dark)").matches)&&document.body.classList.add(e);var d=sessionStorage.getItem(E),A=d!==n&&!window.matchMedia(`screen and (max-width: ${768}px)`).matches;document.body.classList.toggle(a,A);var c=sessionStorage.getItem(r);c&&document.body.style.setProperty("--sidebarWidth",`${c}px`);var p=/(Macintosh|iPhone|iPad|iPod)/.test(window.navigator.userAgent);document.documentElement.classList.toggle("apple-os",p);})();
</script>

<div class="body-wrapper">

<button id="sidebar-menu" class="sidebar-button sidebar-toggle" aria-label="toggle sidebar" aria-controls="sidebar">
  <i class="ri-menu-line ri-lg" title="Collapse/expand sidebar"></i>
</button>

<nav id="sidebar" class="sidebar">

  <div class="sidebar-header">
    <div class="sidebar-projectInfo">

        <a href="https://elixir-lang.org/docs.html" class="sidebar-projectImage">
          <img src="assets/logo.png" alt="Elixir" />
        </a>

      <div>
        <a href="https://elixir-lang.org/docs.html" class="sidebar-projectName" translate="no">
Elixir
        </a>
        <div class="sidebar-projectVersion" translate="no">
          v1.17.3
        </div>
      </div>
    </div>
    <ul id="sidebar-list-nav" class="sidebar-list-nav" role="tablist" data-extras=""></ul>
  </div>
</nav>

<output role="status" id="toast"></output>

<main class="content page-extra" id="main" data-type="extras">
  <div id="content" class="content-inner">
    <div class="top-search">
      <div class="search-settings">
        <form class="search-bar" action="search.html">
          <label class="search-label">
            <span class="sr-only">Search documentation of Elixir</span>
            <input name="q" type="text" class="search-input" placeholder="Press / to search" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" />
          </label>
          <button type="submit" class="search-button" aria-label="Submit Search" tabindex="-1">
            <i class="ri-search-2-line ri-lg" aria-hidden="true"></i>
          </button>
          <button type="button" tabindex="-1" class="search-close-button" aria-hidden="true">
            <i class="ri-close-line ri-lg" title="Cancel search"></i>
          </button>
        </form>
        <div class="autocomplete">
        </div>
        <button class="icon-settings display-settings">
          <i class="ri-settings-3-line"></i>
          <span class="sr-only">Settings</span>
        </button>
      </div>
    </div>

<div id="top-content">
  <div class="heading-with-actions top-heading">
    <h1>try, catch, and rescue</h1>


      <a href="https://github.com/elixir-lang/elixir/blob/cee31ab46f2cd47a942d236470216376b53fb41a/lib/elixir/pages/getting-started/try-catch-and-rescue.md#L1" title="View Source" class="icon-action" rel="help">
        <i class="ri-code-s-slash-line" aria-hidden="true"></i>
        <span class="sr-only">View Source</span>
      </a>

  </div>

<p>Elixir has three error mechanisms: errors, throws, and exits. In this chapter, we will explore each of them and include remarks about when each should be used.</p><h2 id="errors" class="section-heading">
  <a href="#errors" class="hover-link">
    <i class="ri-link-m" aria-hidden="true"></i>
  </a>
  <span class="text">Errors</span>
</h2>
<p>Errors (or <em>exceptions</em>) are used when exceptional things happen in the code. A sample error can be retrieved by trying to add a number to an atom:</p><pre class="elixir" data-code-id="31353436"><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">:foo + 1</span><span class="info"></span></div><p class="output output-initial" data-code-type="output"># ** (ArithmeticError) bad argument in arithmetic expression</p><p class="output output-initial" data-code-type="output">#      :erlang.+(:foo, 1)</p></pre><p>A runtime error can be raised any time by using <a href="Kernel.html#raise/1"><code class="inline">raise/1</code></a>:</p><pre class="elixir" data-code-id="31363130"><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">raise &quot;oops&quot;</span><span class="info"></span></div><p class="output output-initial" data-code-type="output"># ** (RuntimeError) oops</p></pre><p>Other errors can be raised with <a href="Kernel.html#raise/2"><code class="inline">raise/2</code></a> passing the error name and a list of keyword arguments:</p><pre class="elixir" data-code-id="31363734"><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">raise ArgumentError, message: &quot;invalid argument foo&quot;</span><span class="info"></span></div><p class="output output-initial" data-code-type="output"># ** (ArgumentError) invalid argument foo</p></pre><p>You can also define your own errors by creating a module and using the <a href="Kernel.html#defexception/1"><code class="inline">defexception/1</code></a> construct inside it. This way, you'll create an error with the same name as the module it's defined in. The most common case is to define a custom exception with a message field:</p><pre class="elixir" data-code-id="31373338"><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">defmodule MyError do
  defexception message: &quot;default message&quot;
end</span><span class="info"></span></div><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">raise MyError</span><span class="info"></span></div><p class="output output-initial" data-code-type="output"># ** (MyError) default message</p><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">raise MyError, message: &quot;custom message&quot;</span><span class="info"></span></div><p class="output output-initial" data-code-type="output"># ** (MyError) custom message</p></pre><p>Errors can be <strong>rescued</strong> using the <code class="inline">try/rescue</code> construct:</p><pre class="elixir" data-code-id="31383032"><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">try do
  raise &quot;oops&quot;
rescue
  e in RuntimeError -&gt; e
end</span><span class="info"></span></div><p class="output output-initial" data-code-type="output"># %RuntimeError{message: &quot;oops&quot;}</p></pre><p>The example above rescues the runtime error and returns the exception itself, which is then printed in the <code class="inline">iex</code> session.</p><p>If you don't have any use for the exception, you don't have to pass a variable to <code class="inline">rescue</code>:</p><pre class="elixir" data-code-id="31383636"><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">try do
  raise &quot;oops&quot;
rescue
  RuntimeError -&gt; &quot;Error!&quot;
end</span><span class="info"></span></div><p class="output output-initial" data-code-type="output"># &quot;Error!&quot;</p></pre><p>In practice, Elixir developers rarely use the <code class="inline">try/rescue</code> construct. For example, many languages would force you to rescue an error when a file cannot be opened successfully. Elixir instead provides a <a href="File.html#read/1"><code class="inline">File.read/1</code></a> function which returns a tuple containing information about whether the file was opened successfully:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="nc">File</span><span class="o">.</span><span class="n">read</span><span class="p" data-group-id="9039786589-1">(</span><span class="s">&quot;hello&quot;</span><span class="p" data-group-id="9039786589-1">)</span><span class="w">
</span><span class="p" data-group-id="9039786589-2">{</span><span class="ss">:error</span><span class="p">,</span><span class="w"> </span><span class="ss">:enoent</span><span class="p" data-group-id="9039786589-2">}</span><span class="w">
</span><span class="gp unselectable">iex&gt; </span><span class="nc">File</span><span class="o">.</span><span class="n">write</span><span class="p" data-group-id="9039786589-3">(</span><span class="s">&quot;hello&quot;</span><span class="p">,</span><span class="w"> </span><span class="s">&quot;world&quot;</span><span class="p" data-group-id="9039786589-3">)</span><span class="w">
</span><span class="ss">:ok</span><span class="w">
</span><span class="gp unselectable">iex&gt; </span><span class="nc">File</span><span class="o">.</span><span class="n">read</span><span class="p" data-group-id="9039786589-4">(</span><span class="s">&quot;hello&quot;</span><span class="p" data-group-id="9039786589-4">)</span><span class="w">
</span><span class="p" data-group-id="9039786589-5">{</span><span class="ss">:ok</span><span class="p">,</span><span class="w"> </span><span class="s">&quot;world&quot;</span><span class="p" data-group-id="9039786589-5">}</span></code></pre><p>There is no <code class="inline">try/rescue</code> here. In case you want to handle multiple outcomes of opening a file, you can use pattern matching using the <code class="inline">case</code> construct:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="k">case</span><span class="w"> </span><span class="nc">File</span><span class="o">.</span><span class="n">read</span><span class="p" data-group-id="4696524573-1">(</span><span class="s">&quot;hello&quot;</span><span class="p" data-group-id="4696524573-1">)</span><span class="w"> </span><span class="k" data-group-id="4696524573-2">do</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="p" data-group-id="4696524573-3">{</span><span class="ss">:ok</span><span class="p">,</span><span class="w"> </span><span class="n">body</span><span class="p" data-group-id="4696524573-3">}</span><span class="w"> </span><span class="o">-&gt;</span><span class="w"> </span><span class="nc">IO</span><span class="o">.</span><span class="n">puts</span><span class="p" data-group-id="4696524573-4">(</span><span class="s">&quot;Success: </span><span class="si" data-group-id="4696524573-5">#{</span><span class="n">body</span><span class="si" data-group-id="4696524573-5">}</span><span class="s">&quot;</span><span class="p" data-group-id="4696524573-4">)</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="p" data-group-id="4696524573-6">{</span><span class="ss">:error</span><span class="p">,</span><span class="w"> </span><span class="n">reason</span><span class="p" data-group-id="4696524573-6">}</span><span class="w"> </span><span class="o">-&gt;</span><span class="w"> </span><span class="nc">IO</span><span class="o">.</span><span class="n">puts</span><span class="p" data-group-id="4696524573-7">(</span><span class="s">&quot;Error: </span><span class="si" data-group-id="4696524573-8">#{</span><span class="n">reason</span><span class="si" data-group-id="4696524573-8">}</span><span class="s">&quot;</span><span class="p" data-group-id="4696524573-7">)</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="4696524573-2">end</span></code></pre><p>For the cases where you do expect a file to exist (and the lack of that file is truly an <em>error</em>) you may use <a href="File.html#read!/1"><code class="inline">File.read!/1</code></a>:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="nc">File</span><span class="o">.</span><span class="n">read!</span><span class="p" data-group-id="0109204230-1">(</span><span class="s">&quot;unknown&quot;</span><span class="p" data-group-id="0109204230-1">)</span><span class="w">
</span><span class="gt">** (File.Error) could not read file &quot;unknown&quot;: no such file or directory
    (elixir) lib/file.ex:272: File.read!/1</span></code></pre><p>At the end of the day, it's up to your application to decide if an error while opening a file is exceptional or not. That's why Elixir doesn't impose exceptions on <a href="File.html#read/1"><code class="inline">File.read/1</code></a> and many other functions. Instead, it leaves it up to the developer to choose the best way to proceed.</p><p>Many functions in the standard library follow the pattern of having a counterpart that raises an exception instead of returning tuples to match against. The convention is to create a function (<code class="inline">foo</code>) which returns <code class="inline">{:ok, result}</code> or <code class="inline">{:error, reason}</code> tuples and another function (<code class="inline">foo!</code>, same name but with a trailing <code class="inline">!</code>) that takes the same arguments as <code class="inline">foo</code> but which raises an exception if there's an error. <code class="inline">foo!</code> should return the result (not wrapped in a tuple) if everything goes fine. The <a href="File.html"><code class="inline">File</code></a> module is a good example of this convention.</p><h3 id="fail-fast-let-it-crash" class="section-heading">
  <a href="#fail-fast-let-it-crash" class="hover-link">
    <i class="ri-link-m" aria-hidden="true"></i>
  </a>
  <span class="text">Fail fast / Let it crash</span>
</h3>
<p>One saying that is common in the Erlang community, as well as Elixir's, is &quot;fail fast&quot; / &quot;let it crash&quot;. The idea behind let it crash is that, in case something <em>unexpected</em> happens, it is best to let the exception happen, without rescuing it.</p><p>It is important to emphasize the word <em>unexpected</em>. For example, imagine you are building a script to process files. Your script receives filenames as inputs. It is expected that users may make mistakes and provide unknown filenames. In this scenario, while you could use <a href="File.html#read!/1"><code class="inline">File.read!/1</code></a> to read files and let it crash in case of invalid filenames, it probably makes more sense to use <a href="File.html#read/1"><code class="inline">File.read/1</code></a> and provide users of your script with a clear and precise feedback of what went wrong.</p><p>Other times, you may fully expect a certain file to exist, and in case it does not, it means something terribly wrong has happened elsewhere. In such cases, <a href="File.html#read!/1"><code class="inline">File.read!/1</code></a> is all you need.</p><p>The second approach also works because, as discussed in the <a href="processes.html">Processes</a> chapter, all Elixir code runs inside processes that are isolated and don't share anything by default. Therefore, an unhandled exception in a process will never crash or corrupt the state of another process. This allows us to define supervisor processes, which are meant to observe when a process terminates unexpectedly, and start a new one in its place.</p><p>At the end of the day, &quot;fail fast&quot; / &quot;let it crash&quot; is a way of saying that, when <em>something unexpected</em> happens, it is best to start from scratch within a new process, freshly started by a supervisor, rather than blindly trying to rescue all possible error cases without the full context of when and how they can happen.</p><h3 id="reraise" class="section-heading">
  <a href="#reraise" class="hover-link">
    <i class="ri-link-m" aria-hidden="true"></i>
  </a>
  <span class="text">Reraise</span>
</h3>
<p>While we generally avoid using <code class="inline">try/rescue</code> in Elixir, one situation where we may want to use such constructs is for observability/monitoring. Imagine you want to log that something went wrong, you could do:</p><pre><code class="makeup elixir" translate="no"><span class="k">try</span><span class="w"> </span><span class="k" data-group-id="3650634149-1">do</span><span class="w">
  </span><span class="n">...</span><span class="w"> </span><span class="n">some</span><span class="w"> </span><span class="n">code</span><span class="w"> </span><span class="n">...</span><span class="w">
</span><span class="k" data-group-id="3650634149-1">rescue</span><span class="w">
  </span><span class="n">e</span><span class="w"> </span><span class="o">-&gt;</span><span class="w">
    </span><span class="nc">Logger</span><span class="o">.</span><span class="n">error</span><span class="p" data-group-id="3650634149-2">(</span><span class="nc">Exception</span><span class="o">.</span><span class="n">format</span><span class="p" data-group-id="3650634149-3">(</span><span class="ss">:error</span><span class="p">,</span><span class="w"> </span><span class="n">e</span><span class="p">,</span><span class="w"> </span><span class="c">__STACKTRACE__</span><span class="p" data-group-id="3650634149-3">)</span><span class="p" data-group-id="3650634149-2">)</span><span class="w">
    </span><span class="n">reraise</span><span class="w"> </span><span class="n">e</span><span class="p">,</span><span class="w"> </span><span class="c">__STACKTRACE__</span><span class="w">
</span><span class="k" data-group-id="3650634149-1">end</span></code></pre><p>In the example above, we rescued the exception, logged it, and then re-raised it. We use the <code class="inline">__STACKTRACE__</code> construct both when formatting the exception and when re-raising. This ensures we reraise the exception as is, without changing value or its origin.</p><p>Generally speaking, we take errors in Elixir literally: they are reserved for unexpected and/or exceptional situations, never for controlling the flow of our code. In case you actually need flow control constructs, <em>throws</em> should be used. That's what we are going to see next.</p><h2 id="throws" class="section-heading">
  <a href="#throws" class="hover-link">
    <i class="ri-link-m" aria-hidden="true"></i>
  </a>
  <span class="text">Throws</span>
</h2>
<p>In Elixir, a value can be thrown and later be caught. <code class="inline">throw</code> and <code class="inline">catch</code> are reserved for situations where it is not possible to retrieve a value unless by using <code class="inline">throw</code> and <code class="inline">catch</code>.</p><p>Those situations are quite uncommon in practice except when interfacing with libraries that do not provide a proper API. For example, let's imagine the <a href="Enum.html"><code class="inline">Enum</code></a> module did not provide any API for finding a value and that we needed to find the first multiple of 13 in a list of numbers:</p><pre class="elixir" data-code-id="31393330"><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">try do
  Enum.each(-50..50, fn x -&gt;
    if rem(x, 13) == 0, do: throw(x)
  end)
  &quot;Got nothing&quot;
catch
  x -&gt; &quot;Got #{x}&quot;
end</span><span class="info"></span></div><p class="output output-initial" data-code-type="output"># &quot;Got -39&quot;</p></pre><p>Since <a href="Enum.html"><code class="inline">Enum</code></a> <em>does</em> provide a proper API, in practice <a href="Enum.html#find/2"><code class="inline">Enum.find/2</code></a> is the way to go:</p><pre class="elixir" data-code-id="31393934"><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">Enum.find(-50..50, &amp;(rem(&amp;1, 13) == 0))</span><span class="info"></span></div><p class="output output-initial" data-code-type="output"># -39</p></pre><h2 id="exits" class="section-heading">
  <a href="#exits" class="hover-link">
    <i class="ri-link-m" aria-hidden="true"></i>
  </a>
  <span class="text">Exits</span>
</h2>
<p>All Elixir code runs inside processes that communicate with each other. When a process dies of &quot;natural causes&quot; (e.g., unhandled exceptions), it sends an <code class="inline">exit</code> signal. A process can also die by explicitly sending an <code class="inline">exit</code> signal:</p><pre class="elixir" data-code-id="32303538"><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">spawn_link(fn -&gt; exit(1) end)</span><span class="info"></span></div><p class="output output-initial" data-code-type="output"># ** (EXIT from #PID&lt;0.56.0&gt;) shell process exited with reason: 1</p></pre><p>In the example above, the linked process died by sending an <code class="inline">exit</code> signal with a value of 1. The Elixir shell automatically handles those messages and prints them to the terminal.</p><p><code class="inline">exit</code> can also be &quot;caught&quot; using <code class="inline">try/catch</code>:</p><pre class="elixir" data-code-id="32313232"><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">try do
  exit(&quot;I am exiting&quot;)
catch
  :exit, _ -&gt; &quot;not really&quot;
end</span><span class="info"></span></div><p class="output output-initial" data-code-type="output"># &quot;not really&quot;</p></pre><p><code class="inline">catch</code> can also be used within a function body without a matching <code class="inline">try</code>.</p><pre class="elixir" data-code-id="32313836"><p class="output output-initial" data-code-type="output"># defmodule Example do</p><p class="output output-initial" data-code-type="output">#   def matched_catch do</p><p class="output output-initial" data-code-type="output">#     exit(:timeout)</p><p class="output output-initial" data-code-type="output">#   catch</p><p class="output output-initial" data-code-type="output">#     :exit, :timeout -&gt;</p><p class="output output-initial" data-code-type="output">#       {:error, :timeout}</p><p class="output output-initial" data-code-type="output">#   end</p><p class="output output-initial" data-code-type="output">#   def mismatched_catch do</p><p class="output output-initial" data-code-type="output">#     exit(:timeout)</p><p class="output output-initial" data-code-type="output">#   catch</p><p class="output output-initial" data-code-type="output">#     # Since no clause matches, this catch will have no effect</p><p class="output output-initial" data-code-type="output">#     :exit, :explosion -&gt;</p><p class="output output-initial" data-code-type="output">#       {:error, :explosion}</p><p class="output output-initial" data-code-type="output">#   end</p><p class="output output-initial" data-code-type="output"># end</p></pre><p>However, using <code class="inline">try/catch</code> is already uncommon and using it to catch exits is even rarer.</p><p><code class="inline">exit</code> signals are an important part of the fault tolerant system provided by the Erlang VM. Processes usually run under supervision trees which are themselves processes that listen to <code class="inline">exit</code> signals from the supervised processes. Once an <code class="inline">exit</code> signal is received, the supervision strategy kicks in and the supervised process is restarted.</p><p>It is exactly this supervision system that makes constructs like <code class="inline">try/catch</code> and <code class="inline">try/rescue</code> so uncommon in Elixir. Instead of rescuing an error, we'd rather &quot;fail fast&quot; since the supervision tree will guarantee our application will go back to a known initial state after the error.</p><h2 id="after" class="section-heading">
  <a href="#after" class="hover-link">
    <i class="ri-link-m" aria-hidden="true"></i>
  </a>
  <span class="text">After</span>
</h2>
<p>Sometimes it's necessary to ensure that a resource is cleaned up after some action that could potentially raise an error. The <code class="inline">try/after</code> construct allows you to do that. For example, we can open a file and use an <code class="inline">after</code> clause to close it -- even if something goes wrong:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="p" data-group-id="5550326852-1">{</span><span class="ss">:ok</span><span class="p">,</span><span class="w"> </span><span class="n">file</span><span class="p" data-group-id="5550326852-1">}</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nc">File</span><span class="o">.</span><span class="n">open</span><span class="p" data-group-id="5550326852-2">(</span><span class="s">&quot;sample&quot;</span><span class="p">,</span><span class="w"> </span><span class="p" data-group-id="5550326852-3">[</span><span class="ss">:utf8</span><span class="p">,</span><span class="w"> </span><span class="ss">:write</span><span class="p" data-group-id="5550326852-3">]</span><span class="p" data-group-id="5550326852-2">)</span><span class="w">
</span><span class="gp unselectable">iex&gt; </span><span class="k">try</span><span class="w"> </span><span class="k" data-group-id="5550326852-4">do</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="nc">IO</span><span class="o">.</span><span class="n">write</span><span class="p" data-group-id="5550326852-5">(</span><span class="n">file</span><span class="p">,</span><span class="w"> </span><span class="s">&quot;olá&quot;</span><span class="p" data-group-id="5550326852-5">)</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="k">raise</span><span class="w"> </span><span class="s">&quot;oops, something went wrong&quot;</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="5550326852-4">after</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="nc">File</span><span class="o">.</span><span class="n">close</span><span class="p" data-group-id="5550326852-6">(</span><span class="n">file</span><span class="p" data-group-id="5550326852-6">)</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="5550326852-4">end</span><span class="w">
</span><span class="gt">** (RuntimeError) oops, something went wrong</span></code></pre><p>The <code class="inline">after</code> clause will be executed regardless of whether or not the tried block succeeds. Note, however, that if a linked process exits,
this process will exit and the <code class="inline">after</code> clause will not get run. Thus <code class="inline">after</code> provides only a soft guarantee. Luckily, files in Elixir are also linked to the current processes and therefore they will always get closed if the current process crashes, independent of the
<code class="inline">after</code> clause. You will find the same to be true for other resources like ETS tables, sockets, ports and more.</p><p>Sometimes you may want to wrap the entire body of a function in a <code class="inline">try</code> construct, often to guarantee some code will be executed afterwards. In such cases, Elixir allows you to omit the <code class="inline">try</code> line:</p><pre class="elixir" data-code-id="32323530"><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">defmodule RunAfter do
  def without_even_trying do
    raise &quot;oops&quot;
  after
    IO.puts &quot;cleaning up!&quot;
  end
end</span><span class="info"></span></div><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">RunAfter.without_even_trying</span><span class="info"></span></div><p class="output output-initial" data-code-type="output"># cleaning up!</p><p class="output output-initial" data-code-type="output"># ** (RuntimeError) oops</p></pre><p>Elixir will automatically wrap the function body in a <code class="inline">try</code> whenever one of <code class="inline">after</code>, <code class="inline">rescue</code> or <code class="inline">catch</code> is specified.</p><h2 id="else" class="section-heading">
  <a href="#else" class="hover-link">
    <i class="ri-link-m" aria-hidden="true"></i>
  </a>
  <span class="text">Else</span>
</h2>
<p>If an <code class="inline">else</code> block is present, it will match on the results of the <code class="inline">try</code> block whenever the <code class="inline">try</code> block finishes without a throw or an error.</p><pre class="elixir" data-code-id="32333134"><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">x = 2</span><span class="info"></span></div><p class="output output-initial" data-code-type="output"># 2</p><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">try do
  1 / x
rescue
  ArithmeticError -&gt;
    :infinity
else
  y when y &lt; 1 and y &gt; -1 -&gt;
    :small
  _ -&gt;
    :large
end</span><span class="info"></span></div><p class="output output-initial" data-code-type="output"># :small</p></pre><p>Exceptions in the <code class="inline">else</code> block are not caught. If no pattern inside the <code class="inline">else</code> block matches, an exception will be raised; this exception is not caught by the current <code class="inline">try/catch/rescue/after</code> block.</p><h2 id="variables-scope" class="section-heading">
  <a href="#variables-scope" class="hover-link">
    <i class="ri-link-m" aria-hidden="true"></i>
  </a>
  <span class="text">Variables scope</span>
</h2>
<p>Similar to <code class="inline">case</code>, <code class="inline">cond</code>, <code class="inline">if</code> and other constructs in Elixir, variables defined inside <code class="inline">try/catch/rescue/after</code> blocks do not leak to the outer context. In other words, this code is invalid:</p><pre class="elixir" data-code-id="32333738"><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">try do
  raise &quot;fail&quot;
  what_happened = :did_not_raise
rescue
  _ -&gt; what_happened = :rescued
end</span><span class="info"></span></div><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">what_happened</span><span class="info"></span></div><p class="output output-initial" data-code-type="output"># ** (CompileError) undefined variable &quot;what_happened&quot;</p></pre><p>Instead, you should return the value of the <code class="inline">try</code> expression:</p><pre class="elixir" data-code-id="32343432"><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">what_happened =
  try do
    raise &quot;fail&quot;
    :did_not_raise
  rescue
    _ -&gt; :rescued
  end</span><span class="info"></span></div><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">what_happened</span><span class="info"></span></div><p class="output output-initial" data-code-type="output"># :rescued</p></pre><p>Furthermore, variables defined in the do-block of <code class="inline">try</code> are not available inside <code class="inline">rescue/after/else</code> either. This is because the <code class="inline">try</code> block may fail at any moment and therefore the variables may have never been bound in the first place. So this also isn't valid:</p><pre class="elixir" data-code-id="32353036"><div class="line" data-code-state="NOT_EVALUATED"><span class="prompt">iex&gt;</span><span class="input" data-code-type="input">try do
  raise &quot;fail&quot;
  another_what_happened = :did_not_raise
rescue
  _ -&gt; another_what_happened
end</span><span class="info"></span></div><p class="output output-initial" data-code-type="output"># ** (CompileError) undefined variable &quot;another_what_happened&quot;</p></pre><p>This finishes our introduction on <code class="inline">try</code>, <code class="inline">catch</code>, and <code class="inline">rescue</code>. You will find they are used less frequently in Elixir than in other languages. Next we will talk about a very important subject to Elixir developers: writing documentation.</p>
</div>

<div class="bottom-actions" id="bottom-actions">
  <div class="bottom-actions-item">

      <a href="sigils.html" class="bottom-actions-button" rel="prev">
        <span class="subheader">
          ← Previous Page
        </span>
        <span class="title">
Sigils
        </span>
      </a>

  </div>
  <div class="bottom-actions-item">

      <a href="writing-documentation.html" class="bottom-actions-button" rel="next">
        <span class="subheader">
          Next Page →
        </span>
        <span class="title">
Writing documentation
        </span>
      </a>

  </div>
</div>
    <footer class="footer">
      <p>

        <span class="line">
          <button class="a-main footer-button display-quick-switch" title="Search HexDocs packages">
            Search HexDocs
          </button>

            <a href="Elixir.epub" title="ePub version">
              Download ePub version
            </a>

        </span>
      </p>

      <p class="built-using">
        Built using
        <a href="https://github.com/elixir-lang/ex_doc" title="ExDoc" target="_blank" rel="help noopener" translate="no">ExDoc</a> (v0.37.1) for the

          <a href="https://elixir-lang.org" title="Elixir" target="_blank" translate="no">Elixir programming language</a>

      </p>

    </footer>
  </div>
</main>
</div>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10.2.3/dist/mermaid.min.js"></script>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    mermaid.initialize({
      startOnLoad: false,
      theme: document.body.className.includes("dark") ? "dark" : "default"
    });
    let id = 0;
    for (const codeEl of document.querySelectorAll("pre code.mermaid")) {
      const preEl = codeEl.parentElement;
      const graphDefinition = codeEl.textContent;
      const graphEl = document.createElement("div");
      const graphId = "mermaid-graph-" + id++;
      mermaid.render(graphId, graphDefinition).then(({svg, bindFunctions}) => {
        graphEl.innerHTML = svg;
        bindFunctions?.(graphEl);
        preEl.insertAdjacentElement("afterend", graphEl);
        preEl.remove();
      });
    }
  });
</script>

  </body>
</html>
